# Generated by Django 2.0.2 on 2018-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_native'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Native',
        ),
        migrations.AddField(
            model_name='apitest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apitest',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitest',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pic/'),
        ),
        migrations.AddField(
            model_name='apitest',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
