# Generated by Django 2.0.2 on 2018-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pic/'),
        ),
    ]
