# Generated by Django 2.0.2 on 2018-03-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('body', models.TextField()),
                ('pic', models.FileField(blank=True, null=True, upload_to='pic/')),
            ],
        ),
    ]
